import { type Metadata } from "next";
import { Montserrat } from "next/font/google";

import type { TLayout } from "types";
import Footer from "~/components/shared/footer";
import Navbar from "~/components/shared/navbar";

import "~/styles/globals.css";


const font = Montserrat({
  subsets: ["latin"],
  variable: "--font-sans",
});


export const metadata: Metadata = {
  title: "Expense Tracker",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};


export default function RootLayout({ children }: TLayout) {
  return (
    <html lang="en">
      <body className={`${font.className}`}>
        <Navbar />
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
